import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css"
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import 'swiper/css';
import { Swiper } from 'swiper/react';
import { Autoplay } from 'swiper/modules';
import { Toaster } from "sonner";
import Providers from "@/Providers";
import Footer from "./_components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Toaster richColors position="top-center" />
          <Navbar />
          {children}
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
